options(shiny.maxRequestSize=30*1024^2)

list.of.packages <- c("TTR","readxl","plyr","data.table","tseries","ggplot2", "sqldf", "bcrypt","shiny","shinyBS", "shinyjs", "shinythemes", "lubridate", "Cairo", "psych", "DT", "xtable","tables", "forecast")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
update.packages(list.of.packages)
print(new.packages)


library(sqldf)
library(bcrypt)
library(shiny)
library(shinyBS)
library(shinyjs)
library(shinythemes)
library(lubridate)
library(Cairo)
library(psych)
library(DT)
library(xtable)
library(tables)
library('ggplot2')
library('forecast')
library('tseries')
library(data.table)
library(plyr)
library(readxl)
library(TTR)

data_val <- c()
week_timestamp <- c()
servicelist<-c()
severity<-c()
forecast_val<-c()
MAX_servicelength <-10
final_val<-c()
final_vals<-c()
vector_freq<-c()
ARIMA_mat <- c()
HW_mat <- c()
Croston_mat <- c()
MA_mat <- c()
error_mat<-list()
final_err<-c()
download_data<-c()
summary_algo<-c()
isRecommended <- FALSE
#source("utils/db.R")
#source("utils/logic.R")
#source("utils/init.R")

source("ui.R")
source("server.R")
shinyApp(ui, server)

